version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.6
  install:
    - requirements: requirement.txt
    - requirements: docs/sphinx_requirement.txt
    - method: pip
    
conda:
  file: docs/environment.yml
