language: python

sudo: false

python:
  - "2.7"
  - "3.6"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION pip pytest numpy pandas scipy matplotlib scikit-learn
  - source activate testenv
  - pip install python-coveralls
  - pip install -r requirements.txt
  - pip install -r optional-dependencies.txt
  - python setup.py install
  - pip install git+https://github.com/nilearn/nilearn --upgrade

script: coverage run --source nltools -m py.test

after_success:
  - coveralls
