name: nltools-tutorial

channels:
  - conda-forge

dependencies:
  - python=3.6
  - matplotlib
  - scikit-learn>=0.19.1
  - numpy>=1.9
  - pandas>=0.20
  - seaborn>=0.7.0
  - scipy

  - pip:
    - nilearn>=0.4.1
    - sphinx >= 1.5
    - sphinx-gallery
    - sphinxcontrib-napoleon
    - sphinx_bootstrap_theme
    - requests
    - importlib
    - nibabel>=2.0.1
    - nilearn>=0.4
    - nltools
    - pynv
