channels:
  - conda-forge

name:
  - nltools >= 0.3.12

dependencies:
  - python >= 3.6
  - pip
  - pip:
    - sphinx >= 2.0
    - sphinx-gallery >= 0.3.1
    - sphinxcontrib-napoleon
    - sphinx_bootstrap_theme >= 0.7.1
    - networkx >= 2.3
