channels:
  - conda-forge

name:
  - nltools

dependencies:
  - python=3.5
  - pip
  - pip:
    - sphinx >= 1.5
    - sphinx-gallery
    - sphinxcontrib-napoleon
    - sphinx_bootstrap_theme
    - networkx
